# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ht-devops-service-conn'
    subscriptionId: '266adbeb-3ea4-4c96-9786-39e27c468655'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'HT-Resource-Grp'
    location: 'Central India'
    templateLocation: 'Linked artifact'
    csmFile: 'template.bicep'
    csmParametersFile: 'param_values.json'
    deploymentMode: 'Incremental'
