# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Rushi-Bicep

pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'hoonartek-devops-servicce-connection'
    subscriptionId: 'b7c2a37f-9419-49d2-b35b-388993d1b848'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Hoonartek-devops-2024'
    location: 'Central India'
    templateLocation: 'Linked artifact'
    csmFile: 'template.bicep'
    csmParametersFile: 'param_values.json'
    deploymentMode: 'Incremental'
