---
- name: Install and configure Apache
  hosts: webserver
  become: yes

  tasks:
    - name: Update package repositories
      apt:
        update_cache: yes

    - name: Install Apache2 and php
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - php
        - libapache2-mod-php
        - php-pgsql
      register: apache_installed

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
      when: apache_installed.changed

    - name: Create index.html file
      copy:
        src: "index.php"
        dest: /var/www/html/index.php
        mode: "0644"
      notify: Restart Apache
  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
