---
- hosts: localhost
  become: yes

  vars:
    db_name: appuser
    db_user: appuser
    db_password: app

  tasks:
    - name: Install PostgreSQL packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql
        - python3-pip
    
    - name: Install python packages
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - psycopg2-binary

    - name: Start and enable services
      service:
        name: postgresql
        state: started
        enabled: yes
    
    - name: Create app database
      postgresql_db:
        state: present
        name: "{{ db_name }}"
      become_user: postgres

    - name: Create db user
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become_user: postgres

    - name: Grant db user access to app db
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: yes
        privs: all
      become_user: postgres

    - name: Allow md5 connection for the db user
      postgresql_pg_hba:
        dest: "/etc/postgresql/14/main/pg_hba.conf"
        contype: host
        databases: all
        method: md5
        users: "{{ db_user }}"
        create: true
      become_user: postgres
      notify: restart postgres

    - name: Execute script
      command: "psql {{ db_name }} -f migration.sql"
      register: sql_response_variable
      become_user: postgres

  handlers:
    - name: restart postgres
      service:
        name: postgresql
        state: restarted